-- 创建用户
CREATE LOGIN user1 WITH PASSWORD='1234', DEFAULT_DATABASE=covid19mon;
CREATE LOGIN user2 WITH PASSWORD='1234', DEFAULT_DATABASE=covid19mon;
CREATE LOGIN user3 WITH PASSWORD='1234', DEFAULT_DATABASE=covid19mon;
